<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_signInBtnPasswordContinue</name>
   <tag></tag>
   <elementGuidId>f99ae6c7-8da0-4772-a4d3-6a1d2b7595cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInBtnPasswordContinue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'signInBtnPasswordContinue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c6912c3-8314-440d-a9be-090a3145c797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth css-ys5yqr</value>
      <webElementGuid>aad4b96e-0344-4bda-a5cb-440b8361f435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a48c474-983f-4d99-ab19-e19cc96ea7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>04c6c1cf-28be-4898-adef-e29dd78882a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInBtnPasswordContinue</value>
      <webElementGuid>9da0e626-4434-443e-aff0-d34383741186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>signInBtnPasswordContinue</value>
      <webElementGuid>067c509b-8c2c-4365-9949-60a55b0255c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ed743a84-9062-48f9-843b-fd57923e103e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e08617b37fc9c3ebea8804a8251c646</value>
      <webElementGuid>591c5856-ad60-4d14-baa2-2bc4e938c7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnPasswordContinue']</value>
      <webElementGuid>4773cee7-ef05-4177-b0ce-464e8348e5c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnPasswordContinue']</value>
      <webElementGuid>7306da02-c733-4b6e-951c-b31c855a8562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'signInBtnPasswordContinue' and (text() = 'signInBtnPasswordContinue' or . = 'signInBtnPasswordContinue')]</value>
      <webElementGuid>4e7838e8-1345-465f-a66f-79c2a21ae52b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
