<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_signInBtnEmailContinue</name>
   <tag></tag>
   <elementGuidId>e368a6ea-f38e-4c4a-a1e5-4fa71ff53da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInBtnEmailContinue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'signInBtnEmailContinue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95186932-f173-46d8-82fe-32fef8f895b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth css-ys5yqr</value>
      <webElementGuid>1b61adea-366f-4d92-bb71-b21a69db4bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29dd78ae-40cd-4d01-bd69-bd257c4e530c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>35ef35ed-98c4-4195-9a9c-1ce0b70940d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInBtnEmailContinue</value>
      <webElementGuid>891367c1-839d-4f30-949b-c8051f685b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>signInBtnEmailContinue</value>
      <webElementGuid>c86f5f64-91c5-4afd-819e-9d15c9e743e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ea8539aa-09f4-47ca-a506-ac8edf6608c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ec3b6aefc86e00ab899397fea11161ce</value>
      <webElementGuid>a1da066d-f2e0-4500-a2c3-298b26e01117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnEmailContinue']</value>
      <webElementGuid>2e04be83-746d-4e04-b644-c7da2ca5257a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnEmailContinue']</value>
      <webElementGuid>70aceef2-fc07-493b-a39f-82caa4e4549f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'signInBtnEmailContinue' and (text() = 'signInBtnEmailContinue' or . = 'signInBtnEmailContinue')]</value>
      <webElementGuid>66d95057-6712-4cc2-8e27-f346b114db4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
