<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Play</name>
   <tag></tag>
   <elementGuidId>da50e80f-4e0e-42ad-a25e-cf42beb40878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Play&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Play']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Play&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>307e970c-3b28-4138-916d-e73de6f460a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-large-play-button ytp-button ytp-large-play-button-red-bg</value>
      <webElementGuid>ff49e854-1805-40f9-bb44-871f73f1dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>37125d32-9cce-4092-bf0c-bf10d1c526a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>dc6e1f48-a702-44d6-ad40-dc480daa688b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>2a16b2d5-5dec-47cb-9882-ab6d13078fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6969748dbd3f71ba77b95460e8878978</value>
      <webElementGuid>d4adf6db-d30b-4fc2-9be6-2851f6ec02a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Play']</value>
      <webElementGuid>0d30a10d-09c7-481f-9415-d6246199e332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Help_Page/Page_QuantumTrades/iframe_iframe</value>
      <webElementGuid>f9cb8f36-0b75-4f02-8a16-697de6969954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Play']</value>
      <webElementGuid>468b9bad-00a0-43eb-8773-bfe58f2ae805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Play' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>630698b5-4245-4028-844b-04ae91d83f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
