<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your password</name>
   <tag></tag>
   <elementGuidId>7039085f-c269-4fe8-8d18-8cb5703581da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInTextPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'signInTextPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter your password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>131534ca-53ef-4971-96b5-3b234ad227dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6e714d0-28e7-4f9d-a5be-536e2518cb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInTextPassword</value>
      <webElementGuid>bd4379b8-a1a0-4b9c-8411-c40b0f088c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f4676b11-48f0-413d-8af7-9d73cc405c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your password</value>
      <webElementGuid>62898932-a0e5-410f-b966-0ed0ac79914f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6e2aca11-7f98-4dfe-a9db-7472d0161fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd css-rijqqd</value>
      <webElementGuid>1483910e-acfe-4348-a588-f8db4b992c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter your password</value>
      <webElementGuid>6320adea-fa6d-40e0-8c25-1b79b2d1e9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d747615489b2331f7d0365dd41f63b32</value>
      <webElementGuid>e18c764d-f586-4c4a-8875-7803decff288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'signInTextPassword']</value>
      <webElementGuid>d93a1a5e-6603-4c24-9da7-955106548a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'signInTextPassword']</value>
      <webElementGuid>72756c0e-0415-4f83-9e53-fda5c41f6b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInTextPassword' and @name = 'password' and @placeholder = 'Please enter your password' and @type = 'password' and (text() = 'Please enter your password' or . = 'Please enter your password')]</value>
      <webElementGuid>a72d8481-7967-43af-83f8-6db8209eb3d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
