<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SignInWithGoogleBtn</name>
   <tag></tag>
   <elementGuidId>9ea658c3-87e1-4415-a085-1c7b52046421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SignInWithGoogleBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'SignInWithGoogleBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sign in with google&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e8ade0b-ea4d-4635-a0f2-74553b572731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButton-colorPrimary css-1k4xp5z</value>
      <webElementGuid>7d4c9325-ab04-4ce7-8278-3caae9543496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>581fcdb7-f3b6-4099-9d9d-127404aa5bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a5cf215-e46e-4891-ae86-003c148a3262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SignInWithGoogleBtn</value>
      <webElementGuid>cd1b6df5-0bad-49f2-a39b-1582642d7656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SignInWithGoogleBtn</value>
      <webElementGuid>37caed45-60e2-4ea4-ba29-8be20d05aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Sign In With Google</value>
      <webElementGuid>701f00bb-0066-4455-b132-7565283057da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8a1060e91f660f535947c1b56ff8674</value>
      <webElementGuid>2e131acf-a3e9-40e4-bb80-5f69eea1de69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'SignInWithGoogleBtn']</value>
      <webElementGuid>5fb1ed85-bd7f-4433-a453-b91d5885805e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'SignInWithGoogleBtn']</value>
      <webElementGuid>768c97a2-0247-446c-9875-c9f242d8a613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'SignInWithGoogleBtn' and (text() = 'SignInWithGoogleBtn' or . = 'SignInWithGoogleBtn')]</value>
      <webElementGuid>7007307b-a742-4509-a5a2-6ce4525cd01c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
