<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter your password</name>
   <tag></tag>
   <elementGuidId>373b1131-b691-4b6a-a0d1-a53e456f441e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInTextPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'signInTextPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter your password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9577db2c-0c02-415b-9102-c60fdb731b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b59374dd-0739-4a7d-ad10-efff4cfc2ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInTextPassword</value>
      <webElementGuid>8c0aa00c-f324-4bc7-8be9-e37c6abd0e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>71323cf3-923a-4d02-89d3-1893ff5db8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your password</value>
      <webElementGuid>181d13ae-19aa-45d2-bb3e-392fdd3bc938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>895fa0bf-4e7f-4ed7-84cd-91123e7261ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd css-rijqqd</value>
      <webElementGuid>edc9941a-f7a9-43a1-90c0-83d19a622380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter your password</value>
      <webElementGuid>fc1688c5-5e1a-46d1-982a-4415c6adcc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d747615489b2331f7d0365dd41f63b32</value>
      <webElementGuid>04b77169-2119-4f54-8de0-200976c38995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'signInTextPassword']</value>
      <webElementGuid>df9f935d-bd19-4a67-9817-7410a09a639a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'signInTextPassword']</value>
      <webElementGuid>1c983b1f-1a41-4072-8c22-8ff69c9ce472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInTextPassword' and @name = 'password' and @placeholder = 'Please enter your password' and @type = 'password' and (text() = 'Please enter your password' or . = 'Please enter your password')]</value>
      <webElementGuid>4a56bba4-fcbe-42fa-bf8e-58476a6df8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
