<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_user-welcome</name>
   <tag></tag>
   <elementGuidId>b6a706b1-0d9d-4301-9dae-d320821c5954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;user-welcome&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'user-welcome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;user-welcome&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7f72eafa-3094-491a-a4f7-577219bbbc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 css-c7rx91</value>
      <webElementGuid>199191c3-81e1-4f5a-9989-32965cb0c35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-welcome</value>
      <webElementGuid>1b2b4763-2b8b-4669-a1a5-f3b02272edcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>user-welcome</value>
      <webElementGuid>04c6e7f4-b41f-45eb-a41d-1ed5e3c3b1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user-welcome</value>
      <webElementGuid>06d5f31a-3ece-4552-bcf0-0ab5d8080854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Welcome Back!</value>
      <webElementGuid>ca3936c6-0142-4d29-9015-ee0285073b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-987b9d79820a3efb60dd972c8b39f0ee</value>
      <webElementGuid>8706a9b7-fcee-49bf-b7a1-9ecbf8b0c718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'user-welcome']</value>
      <webElementGuid>f6283690-4134-4765-aa92-6a2aab38e154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'user-welcome']</value>
      <webElementGuid>eebb5e1f-21ce-459c-a26a-ae165f775fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'user-welcome' and (text() = 'user-welcome' or . = 'user-welcome')]</value>
      <webElementGuid>9f2a3f79-7b9b-42d8-9e4a-8a75c40b8f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
