<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_signInBtnEmailContinue</name>
   <tag></tag>
   <elementGuidId>897fa53a-1e1d-451f-91f9-a0e80dd35ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInBtnEmailContinue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'signInBtnEmailContinue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bfd6294-a112-48d1-9ba6-a8c8ba9e1cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-colorPrimary MuiButton-fullWidth css-ys5yqr</value>
      <webElementGuid>226d66b5-fed6-4d28-8b93-f37d6b53b5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff3d272c-5ee9-4065-82fe-56f5f468e6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>77b43813-efbb-4194-b39d-a74328729c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInBtnEmailContinue</value>
      <webElementGuid>0c799aca-0642-433c-9d2a-986e2916ab21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>signInBtnEmailContinue</value>
      <webElementGuid>14bfa4ba-0cdc-4f88-9488-09337a873c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>fb156044-d562-43bd-b5cb-64a13fc3322e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ec3b6aefc86e00ab899397fea11161ce</value>
      <webElementGuid>90922338-2f00-4e65-bf9e-ad1073091c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnEmailContinue']</value>
      <webElementGuid>721aeebf-1f06-4771-bddb-1dd022218f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'signInBtnEmailContinue']</value>
      <webElementGuid>2263896b-4688-41ac-bc2f-12b134f3ecad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'signInBtnEmailContinue' and (text() = 'signInBtnEmailContinue' or . = 'signInBtnEmailContinue')]</value>
      <webElementGuid>27764c4d-9b67-49e9-abd1-48f258c08c0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
