<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sure The Iron Condor is an options trading st</name>
   <tag></tag>
   <elementGuidId>45523659-3826-4f7f-9084-25d3b0e94d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.bot-reply .reply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bot-reply ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' reply ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Loading....&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ac7ca09-7737-4fe5-9698-ad6066554b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reply</value>
      <webElementGuid>733e11b5-b67a-4d49-acd8-edcfefb8bfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sure! The Iron Condor is an options trading st</value>
      <webElementGuid>7ec91d7e-186b-43b9-85bb-fac4f59193c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Loading....</value>
      <webElementGuid>730f5ec7-7d92-4f53-957d-ab8f93726c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b917b9f0d5d492cd0590486053c397f7</value>
      <webElementGuid>ea049f28-23d3-43d1-b0c2-98df4283a2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bot-reply ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' reply ')]</value>
      <webElementGuid>72644ece-de1b-44d0-afa6-e755b9b66686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bot-reply ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' reply ')]</value>
      <webElementGuid>2f4f27fa-fd99-425e-9818-116aff021b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sure! The Iron Condor is an options trading st' or . = 'Sure! The Iron Condor is an options trading st')]</value>
      <webElementGuid>0163be48-ef47-459f-9be4-3e74283c2357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
