name: Katalon Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: macos-latest  # Using macOS since your environment is on Mac
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Katalon Studio GitHub Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
        version: '9.3.0'  # Using a recent stable version
        projectPath: '${{ github.workspace }}'
        args: '-noSplash -retry=0 -testSuitePath="Test Suites/Test Suite" -browserType="Chrome" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()  # Upload even if tests fail
      with:
        name: test-results
        path: |
          Reports/
          Test Results/ 