name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/Phase 1" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'  
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: test-results
        path: |
          Reports/
          Test Results/ 
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./Reports/
            publish_branch: gh-pages
            keep_files: true
            force_orphan: true
            commit_message: "Deploy PDF report to GitHub Pages"
            exclude_assets: |
                !*.pdf
  
    - name: Send Discord Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ✅ **Test execution completed!**
          📄 View the report at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
      if: always()  # Send even if tests fail
