name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/Phase 1" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'  
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: test-results
        path: |
          Reports/
          Test Results/ 
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./Reports/
            publish_branch: gh-pages
            keep_files: true
            force_orphan: true
            commit_message: "Deploy PDF report to GitHub Pages"
            exclude_assets: |
                !*.pdf

    - name: Send Discord Notification
      run: |
        # Get test results from the latest report
        REPORT_PATH=$(find ./Reports -name "*.pdf" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
        TOTAL_TESTS=$(grep -r "Total Tests" ./Reports | grep -o '[0-9]*' | head -1 || echo "0")
        PASSED_TESTS=$(grep -r "Passed" ./Reports | grep -o '[0-9]*' | head -1 || echo "0")
        FAILED_TESTS=$(grep -r "Failed" ./Reports | grep -o '[0-9]*' | head -1 || echo "0")
        
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{
          "embeds": [{
            "title": "Test Execution Results",
            "color": 5814783,
            "fields": [
              {
                "name": "Total Tests",
                "value": "'$TOTAL_TESTS'",
                "inline": true
              },
              {
                "name": "Passed",
                "value": "'$PASSED_TESTS'",
                "inline": true
              },
              {
                "name": "Failed",
                "value": "'$FAILED_TESTS'",
                "inline": true
              }
            ],
            "description": "📄 [View Detailed Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'$(basename "$REPORT_PATH")')"
          }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK }}
      if: always()  # Send even if tests fail
