name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/Phase 1" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'  
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: test-results
        path: |
          Reports/
          Test Results/ 
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Reports/
        publish_branch: gh-pages
        keep_files: true
        force_orphan: true
        commit_message: "Deploy PDF and HTML report to GitHub Pages"
        exclude_assets: '!*.pdf !*.html'

        
    - name: Send Discord Notification
      run: |
        # Find the latest HTML report
        HTML_REPORT_PATH=$(find ./Reports -name "*.html" -type f | sort | tail -1)
        HTML_REPORT_FILE=$(basename "$HTML_REPORT_PATH")
        REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/$HTML_REPORT_FILE"

        # Example values (replace with actual extraction if needed)
        SUITE_NAME="Test Suites/Verify Operations"
        STATUS="COMPLETE"
        PASSED=0
        FAILED=0
        SKIPPED=0
        DURATION="8 seconds"

        MESSAGE="🧪 Test Suite Execution Report\n\
        📘 Suite\n$SUITE_NAME\n\
        📊 Status\n$STATUS\n\
        ✅ Passed\n$PASSED\n\
        ❌ Failed\n$FAILED\n\
        ⏭️ Skipped\n$SKIPPED\n\
        ⏱️ Duration\n$DURATION\n\
        📄 Report\n[Click to View]($REPORT_URL)"
        
        -X POST \
          -d "{\"content\": \"$MESSAGE\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
      if: always()  # Send even if tests fail
